# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enotifier.proto\x12\tGrpcAgent\" \n\rNotifyRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\" \n\x0bNotifyReply\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x32\x46\n\x08Notifier\x12:\n\x06Notify\x12\x18.GrpcAgent.NotifyRequest\x1a\x16.GrpcAgent.NotifyReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifier_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NOTIFYREQUEST']._serialized_start=29
  _globals['_NOTIFYREQUEST']._serialized_end=61
  _globals['_NOTIFYREPLY']._serialized_start=63
  _globals['_NOTIFYREPLY']._serialized_end=95
  _globals['_NOTIFIER']._serialized_start=97
  _globals['_NOTIFIER']._serialized_end=167
# @@protoc_insertion_point(module_scope)
