# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscriber.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10subscriber.proto\x12\tGrpcAgent\"3\n\x11SubscriberRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"$\n\x0fSubscriberReply\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x32S\n\nSubscriber\x12\x45\n\tSubscribe\x12\x1c.GrpcAgent.SubscriberRequest\x1a\x1a.GrpcAgent.SubscriberReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subscriber_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SUBSCRIBERREQUEST']._serialized_start=31
  _globals['_SUBSCRIBERREQUEST']._serialized_end=82
  _globals['_SUBSCRIBERREPLY']._serialized_start=84
  _globals['_SUBSCRIBERREPLY']._serialized_end=120
  _globals['_SUBSCRIBER']._serialized_start=122
  _globals['_SUBSCRIBER']._serialized_end=205
# @@protoc_insertion_point(module_scope)
